diffusion_augmentation:
  _target_: diffusion_planner.data_augmentation.diffusion_scenario_generator.DiffusionScenarioGenerator
  _convert_: "all"

  history_steps: 21
  low: [-1.0, -0.75, -0.35, -1, -0.5, -0.2, -0.1]
  high: [1.0, 0.75, 0.35, 1, 0.5, 0.2, 0.1]
  max_interaction_horizon: 40
