# @package _global_
job_name: scope
py_func: train
objective_aggregate_mode: mean

defaults:
        - override /data_augmentation:
                  - diffusion_scenario_generator
        - override /splitter: nuplan
        - override /model: diffusion_planner
        - override /scenario_filter: training_scenarios_tiny
        - override /custom_trainer: diffusion_trainer
        - override /lightning: custom_lightning
